### ISSUE TITLE
humidex calculation

### ISSUE THREAD

**Issue by a-nyx** [nshiab/journalism#22]
`getHumidex()` returns 58 given temperature 35 C and humidity %95 but [the reference table](https://www.canada.ca/en/environment-climate-change/services/seasonal-weather-hazards/warm-season-weather-hazards.html#toc7) tells 59.

**Comment by nshiab** [comment]
23 C x 40% humidity = 24 humidex on our interactive, but = 23 humidex on climate data https://www.canada.ca/en/environment-climate-change/services/seasonal-weather-hazards/warm-season-weather-hazards.html#toc7

**Comment by nshiab** [comment]
here is the calculation from ECCC: https://climate.weather.gc.ca/glossary_e.html
